ebook_metadata:
  title: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད།
  authors:
  - མཛད་པ་པོ། ཤཱཀྱ་མཆོག་ལྡན་དྲི་མེད་ལེགས་པའི་བློ་གྲོས།
  sku: RDI-SS-08
  layers:
  - book_title
  - author
  - tsawa
  - quotation
  - sabche
web_metadata:
  title:
    en: Heart of the Ocean of Dharma Prophecies:A Commentary on the Difficult Points
      of “The Ornament of Clear Realization” from the Prajnaparamita
    bo: མངོན་རྟོགས་རྒྱན་གྱི་དཀའ་འགྲེལ་ལུང་ཆོས་རྒྱ་མཚོའི་སྙིང་པོ།
  collection:
    en: RDI Study Series–  Book 8
    bo: ཐོས་བསམ་འཆད་ཉན་གྱི་རིམ་པ།–  དེབ། ༨
  author:
    en: Shakya Chogden Drime Legpai Lodro
    bo: ཤཱཀྱ་མཆོག་ལྡན་དྲི་མེད་ལེགས་པའི་བློ་གྲོས།
  pusblisher:
    en: Rigpe Dorje Institute
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-SS-08
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-SS-08.epub
  description:
    en: ༄༅། །༧རྗེ་བརྒྱད་པ་མི་བསྐྱོད་རྡོ་རྗེས་བཀའ་བར་པའི་དགོངས་དོན་སྦས་དོན་མངོན་རྟོགས་ཀྱི་རིམ་པ་གསལ་བར་བརྗོད་པའི་བསྟན་བཅོས་མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་བ་རྗེ་བཙུན་ངལ་གསོ་ཞེས་པ་ལྗགས་རྩོམ་མཛད།
      དེའི་འགྲེལ་ཚུལ་ཡང་རྩ་བའི་སྐབས་མཛད་པ་པོ་རྗེ་བཙུན་བྱམས་མགོན་དང་ཤིང་རྟའི་སྲོལ་འབྱེད་སློབ་དཔོན་ཐོགས་མེད་ཡབ་སྲས་ཀྱི་དགོངས་པའི་གཏད་སོ་མཐར་ཐུག་ཏུ་གནས་པའི་དབུ་མ་གཞན་སྟོང་ལྟར་དུ་བཀྲལ་བ་དང་།
      འགྲེལ་བ་དོན་གསལ་ནི་སློབ་དཔོན་སེངྒེ་བཟང་པོའི་དགོངས་དོན་བཞིན་དབུ་མ་རང་རྒྱུད་པར་བཀྲལ་བ་ཡིན་ཞེས་རྗེ་བཙུན་མི་བསྐྱོད་རྡོ་རྗེ་རང་ཉིད་ཀྱིས་གསལ་བར་གསུངས་ཀྱང་།
      འདིའི་ཐད་བོད་འགྲེལ་ཕལ་ཆེར་ལས་གསུང་སྒྲོས་ཐ་དད་ཅིང་རྟོགས་དཀའ་བ་དང་། མཐའ་དཔྱོད་གསལ་ཁ་ཅན་འགའ་ཡང་མེད་པས་ཐད་ཀར་རང་སྟོབས་ཀྱིས་འཇུག་དཀའ་བའི་གནས་སུ་མཆིས།
      འོན་ཀྱང་པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན་དྲི་མེད་ལེགས་པའི་བློ་གྲོས་ཀྱིས་མཛད་པའི་ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་འགྲེལ་རྒྱས་བསྡུས་གཉིས་པོ་འདི་ཉིད་གོ་བདེ་ཞིང་གསུང་སྒྲོས་མཐུན་ཤས་ཆེ་བས་རྗེ་མི་བསྐྱོད་ཞབས་ཀྱི་དགོངས་དོན་ནོར་བུའི་བང་མཛོད་སྒོ་འབྱེད་འཕྲུལ་གྱི་ལྡེ་མིག་ལྟ་བུར་སྣང་ངོ་།
      །
    bo: ༄༅། །༧རྗེ་བརྒྱད་པ་མི་བསྐྱོད་རྡོ་རྗེས་བཀའ་བར་པའི་དགོངས་དོན་སྦས་དོན་མངོན་རྟོགས་ཀྱི་རིམ་པ་གསལ་བར་བརྗོད་པའི་བསྟན་བཅོས་མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་བ་རྗེ་བཙུན་ངལ་གསོ་ཞེས་པ་ལྗགས་རྩོམ་མཛད།
      དེའི་འགྲེལ་ཚུལ་ཡང་རྩ་བའི་སྐབས་མཛད་པ་པོ་རྗེ་བཙུན་བྱམས་མགོན་དང་ཤིང་རྟའི་སྲོལ་འབྱེད་སློབ་དཔོན་ཐོགས་མེད་ཡབ་སྲས་ཀྱི་དགོངས་པའི་གཏད་སོ་མཐར་ཐུག་ཏུ་གནས་པའི་དབུ་མ་གཞན་སྟོང་ལྟར་དུ་བཀྲལ་བ་དང་།
      འགྲེལ་བ་དོན་གསལ་ནི་སློབ་དཔོན་སེངྒེ་བཟང་པོའི་དགོངས་དོན་བཞིན་དབུ་མ་རང་རྒྱུད་པར་བཀྲལ་བ་ཡིན་ཞེས་རྗེ་བཙུན་མི་བསྐྱོད་རྡོ་རྗེ་རང་ཉིད་ཀྱིས་གསལ་བར་གསུངས་ཀྱང་།
      འདིའི་ཐད་བོད་འགྲེལ་ཕལ་ཆེར་ལས་གསུང་སྒྲོས་ཐ་དད་ཅིང་རྟོགས་དཀའ་བ་དང་། མཐའ་དཔྱོད་གསལ་ཁ་ཅན་འགའ་ཡང་མེད་པས་ཐད་ཀར་རང་སྟོབས་ཀྱིས་འཇུག་དཀའ་བའི་གནས་སུ་མཆིས།
      འོན་ཀྱང་པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན་དྲི་མེད་ལེགས་པའི་བློ་གྲོས་ཀྱིས་མཛད་པའི་ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་འགྲེལ་རྒྱས་བསྡུས་གཉིས་པོ་འདི་ཉིད་གོ་བདེ་ཞིང་གསུང་སྒྲོས་མཐུན་ཤས་ཆེ་བས་རྗེ་མི་བསྐྱོད་ཞབས་ཀྱི་དགོངས་དོན་ནོར་བུའི་བང་མཛོད་སྒོ་འབྱེད་འཕྲུལ་གྱི་ལྡེ་མིག་ལྟ་བུར་སྣང་ངོ་།
      །
